### ISSUE TITLE
Refactor: Access Control 

### ISSUE THREAD

**Issue by vanderaj** [OWASP/DevGuide#12]
This is a placeholder issue relating to the refactor of the access control chapter. Please place all notes, reviews, defects, etc relating to the access control chapter in here. When the chapter is ready for peer review and graphics, please close this issue.

**Comment by nhajiyani** [comment]
Hi,
I will be happy to assist with this action item

**Comment by bradchesney79** [comment]
I am in the middle of a launch that has been plagued with setbacks and disappointments until recently.

@nhajiyani, I would gladly review any contributions you would like to make and include them in part or in full. If you were looking for a friendly place to make your mark on the world in a positive way-- welcome.

**Comment by nhajiyani** [comment]
@bradchesney79 Let me know the 101 or where to look in to beginning on this task and I will be happy to start on this

**Comment by bradchesney79** [comment]
@nhajiyani Step one is to clone the project. There are a lot of chapters in github flavor markdown format that are empty, sadly. Feel free to jump in to the best of your ability in a section you feel versed in.

**Comment by jgadsden** [comment]
Closing this because the Developer Guide is being migrated to the [new OWASP repo ](https://github.com/OWASP/www-project-developer-guide/issues/23) with revised content
