### ISSUE TITLE
Refactor: Input validation and output encoding chapter

### ISSUE THREAD

**Issue by vanderaj** [OWASP/DevGuide#13]
Please refactor the input validation and output encoding chapters.

There's a very good chance that these two closely related topics should be split into independent chapters. I'm okay with that.

Please make sure that Ajax, DOM, and JSON are talked about in the revised version. Please talk to Jim Manico about best practices in this area. 

When you have finished the first draft and closed out all defects and review notes in this placeholder, please close this issue as it let's us know when the milestone is done.

**Comment by jgadsden** [comment]
Closing this because the Developer Guide is being migrated to the [new OWASP repo ](https://github.com/OWASP/www-project-developer-guide/issues/23) with revised content
