### ISSUE TITLE
GitHub does not have an official image/file upload interface - workaround inside

### ISSUE THREAD

**Issue by bradchesney79** [OWASP/DevGuide#17]
Via drag (from your device/PC) and drop (to GitHub Issues, i.e. here) you can upload to GitHub.

Once it is in the issue, you can view the image resource or page source to see where GitHub is storing it.

**Comment by bradchesney79** [comment]
Github has instituted a file upload interface/utility thingey.

**Comment by DinisCruz** [comment]
quick note, I have been using draw.io for diagrams and it is working really well (since it has both online and offline editing and the raw files are stored in xml, which you can see here https://github.com/DinisCruz/Security-Research/tree/master/pdfs/Threat-Modeling/Concepts )

**Comment by bradchesney79** [comment]
I, at the very least, am switching to draw.io .

Thanks for the heads up about the tool.

**Comment by DinisCruz** [comment]
@bradchesney79 no worries, please share the diagrams that you create
