### ISSUE TITLE
Refactor: Session Management chapter

### ISSUE THREAD

**Issue by vanderaj** [OWASP/DevGuide#26]
Luke, 

I'll spend a bit of time looking over the changes in the next few days and let's make a time to go over the structure and content via a Hangout. 

When is good for you? I'm mostly free 8 pm - midnight most nights Australian Eastern Time (UTC+10).

**Comment by lukos** [comment]
Wow, I waited a long time to reply to this! If you're still interested, I can make most days from 8pm (AET), which is 10am (UTC). I need to reread what is going on as I lapsed when everything went quiet.
