### ISSUE TITLE
The introduction.md stops midsentence!

### ISSUE THREAD

**Issue by drakezhard** [OWASP/DevGuide#35]
It is far harder to write solid code than to destroy it. Necessarily, this book contains a great deal of information. Not every application will require every control, and thus it is necessary to...?

**Comment by kwwall** [comment]
Did you check an earlier revision? I know that I have accidentally cut text
(when I meant to copy) and didn't discover until later that I had deleted
it. Might be the case here.

-kevin

**Comment by frenchi** [comment]
You can always see earlier versions by going to [the file](https://github.com/OWASP/DevGuide/blob/master/00-Introduction/Introduction.md) and clicking on [Blame](https://github.com/OWASP/DevGuide/blame/master/00-Introduction/Introduction.md) or [History](https://github.com/OWASP/DevGuide/commits/master/00-Introduction/Introduction.md).

In this case, we can see it's just [one commit](https://github.com/OWASP/DevGuide/commit/24dbf8ea584b4df546c3983b315771c0a104fbde), which means that I'm the fool that left half a sentence missing. Either I stuffed up the copy+paste, or it wasn't present in the original source.

**Comment by drakezhard** [comment]
I really new to Github, I never really saw the Blame or History button, I'm closing this thanks for the fast response.
