### ISSUE TITLE
Concatenate Markdown Documents and Convert to PDF Document

### ISSUE THREAD

**Issue by bradchesney79** [OWASP/DevGuide#52]
This would allow the guide to be more accessible to everyone as PDF is easier to consume -- it is also probably one of the more easily accomplished things via scripting.

If no one beats me to it, I will likely do this after all chapters are at least populated with basic information.

**Comment by vdbaan** [comment]
I would recommend to create a 'script' folder that contains the scripts. Next to the contents we should be able to have some styling done (like the code review guide).

**Comment by bradchesney79** [comment]
This looks like it could be solved with gitbook. I'll look into it over the next few weeks.

**Comment by jgadsden** [comment]
Hello @bradchesney79 
We do something similar for the Secure Coding Practices Quick Reference Guide using pandoc
Do you want me to provide this for the Developers Guide as well?

**Comment by jgadsden** [comment]
we have moved away from gitbook (see #60 ) and the Developer Guide markdown is being migrated to the [new repo](https://github.com/OWASP/www-project-developer-guide)

there is the intention to [provide PDF ](https://github.com/OWASP/www-project-developer-guide/issues/23)in addition to the web document for this new Developer Guide
