### ISSUE TITLE
Publish on https://www.gitbook.com/@owasp

### ISSUE THREAD

**Issue by bkimminich** [OWASP/DevGuide#60]
Some time ago I created an org for OWASP on GitBook: https://www.gitbook.com/@owasp

If you'd like to publish the DevGuide over there officially, please let me know so I can give access rights to the owner(s) of this GitHub-repo.

**Comment by cmlicata** [comment]
@bkimminich, I'd be happy to do it.

**Comment by bradchesney79** [comment]
I was using a different tool-- but gitbook seems like it would be at least as good at what I was trying to do with the other tool. Was being the operative word. I have admin rights to this repo and would like to publish officially. Thank you.

**Comment by bkimminich** [comment]
@bradchesney79 You should have received an invitation via the email listed on your GitHub profile.

**Comment by ivaaaan** [comment]
Bump. I will be good to publish book in GitBook.

**Comment by bradchesney79** [comment]
I have signed into gitbook and it automatically recognized my organization affiliations-- so that is nice. I'll take a look at the next steps soon.

**Comment by bradchesney79** [comment]
Quasi done...

**Comment by ido-dubrawsky** [comment]
Has this been completed?   Or should I just use the GitBook CLI tool?

**Comment by bradchesney79** [comment]
Cripes, been a bad maintainer-- I would happily accept help in completing this task if you still have the interest and bandwidth.

**Comment by jgadsden** [comment]
@bkimminich the org for OWASP on GitBook: https://www.gitbook.com/@owasp
seems to be empty? I can see the org but cannot see any documents in it - is it still in use?

**Comment by bkimminich** [comment]
Gitbook is a dead horse imho...

**Comment by jgadsden** [comment]
OK, thanks, just checking :)

**Comment by jgadsden** [comment]
closing this as gitbook is no longer required for this project
