### ISSUE TITLE
Nothing related with the repo! PLEASE READ

### ISSUE THREAD

**Issue by JoaoLages** [OWASP/DevGuide#62]
Hi there! SOrry to communicate like this but it was the way I found to reach you directly.
I have seen your post a year ago in stackexchange, https://stats.stackexchange.com/questions/221511/false-positives-in-cosine-similarity, about false positives in TF-IDF cosine. 

I have been getting the same results as you did. I have almost non false negatives and the false positives occur, as you said, because some texts share the right "keywords" between each other.
Can you share with me the way you solved this problem?

Thanks in advance!

**Comment by bradchesney79** [comment]
I will assume that you mean someone else-- do you have a name or even a username for the person you are seeking?
