### ISSUE TITLE
is there any recent version of this guide? this one seems to be bit old.

### ISSUE THREAD

**Issue by monikagupta78** [OWASP/DevGuide#71]

**Comment by bradchesney79** [comment]
It is maintained by volunteers-- it is far from complete. What is complete is meant to be platform agnostic and in a way timeless general best practices...

**Comment by nightwarrior-xxx** [comment]
Usually Guides on GitHub are complete because it is maintained by maintainers and reviewers. Moreover they are one of the best source of study .

**Comment by lukos** [comment]
I've noticed that some sections have been started but not completed, which is unfortunate but is there anything missing that you (@monikagupta78 ) think should be included leading you to say that it "seems a bit old"?

To be honest, not much has changed over the past 5 years with good app security, if anything, some of the older vulnerabilities have become less significant now that many frameworks are much more secure by default now.

**Comment by jgadsden** [comment]
@bradchesney79 and @vdbaan , it would be good to have an updated guide - any news on updates?

**Comment by jgadsden** [comment]
The Developer Guide is now being hosted on OWASP/[www-project-developer-guide](https://github.com/OWASP/www-project-developer-guide)
we may want to archive this repo OWASP/[DevGuide](https://github.com/OWASP/DevGuide)

**Comment by kwwall** [comment]
@jgadsden  and @hblankenship - If you are planning to do a release in the next 6 months or less, let me know and I will review the [Cryptography chapter](https://github.com/OWASP/www-project-developer-guide/blob/main/_draft/0x11-Cryptography.md) and at least complete the **TODO** parts that I left unfinished. I had written those sections up a few years but can no longer seem to find it, but it probably is less than an 8 hour job to reconstruct if I prioritized it. I had just became a really low priority for me because I didn't see much moving on the other chapters. My higher FOSS priorities are ESAPI and assisting on the Cheat Sheet series, so I would appreciate a heads up if this project starts moving again.

**Comment by jgadsden** [comment]
Hello @kwwall - very good to hear from you
Yes, this project is being revived , after all it was the original OWASP publication of them all :)

It has a new team of leaders:
[Andra Lezza](mailto:andra.lezza@owasp.org)
[Shruti Kulkarni](mailto:shruti.kulkarni@owasp.org)
[Vandana Verma](https://github.com/OWASP/www-project-developer-guide/blob/main/vandana.verma@owasp.org)
[Harold Blankenship](mailto:harold.blankenship@owasp.org)
[Jon Gadsden](mailto:jon.gadsden@owasp.org)

We would like to completely reorganise the Developer Guide, and also rewrite some sections, and this process was started at the OWASP AppSec Dublin conference last month. At the moment the [www-project-developer-guide](https://github.com/OWASP/www-project-developer-guide) repo has the (not published) version 3.0 as draft, but this is more of a placeholder than anything

There is the slack channel for this project at OWASP #project-developer-guide, I have added you to the channel

**Comment by jgadsden** [comment]
The intention is to migrate to the [www-project-developer-guide](https://github.com/OWASP/www-project-developer-guide) repo and this repo will entually be archived as Read Only

**Comment by jgadsden** [comment]
Closing this issue because the new draft version is being created [here](https://github.com/OWASP/www-project-developer-guide)
It has yet to have content, but that is in progress, and the intention is to re-use as much of the version 3.0(draft) as is still current
